import { StyleSheet } from "react-native";

export default StyleSheet.create({
     container: {
      flex: 1,
      backgroundColor: '#0e0e14',
    },
    stepContainer: {
      flex: 1,
      alignItems: 'center',
      padding: 30,
    },
    menuContainer: {
      flex: 1,
      justifyContent: 'space-evenly',
      alignItems: 'center',
    },
    label: {
      fontSize: 24,
      color: '#fff',
      marginVertical: 10,
      textAlign: 'center',
    },
    input: {
      width: '100%',
      height: 50,
      borderRadius: 5,
      paddingHorizontal: 10,
      backgroundColor: '#2a2a3d',
      color: '#fff',
      marginVertical: 10,
      fontSize: 18
    },
    dropdownButton: {
      height: 50,
      width: 90,
      backgroundColor: '#2a2a3d',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 5,
      marginVertical: 10,
    },
    dropdownText: {
      color: '#fff',
      fontSize: 16,
    },
    addButton: {
      backgroundColor: '#28a745',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 5,
      marginTop: 20,
    },
    addButtonText: {
      color: '#fff',
      fontSize: 16,
    },
    billItem: {
      color: '#fff',
      fontSize: 16,
      marginVertical: 5,
    },
    navButtons: {
      flexDirection: 'row',
      justifyContent: 'space-evenly',
      marginTop: 20,
      width: '100%',
      position: 'absolute',
      bottom: 20,
    },
    backButton: {
      backgroundColor: '#de4b4b',
      padding: 10,
      borderRadius: 5,
      width: '45%',
      alignItems: 'center',
    },
    backButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: 'bold',
    },
    nextButton: {
      backgroundColor: '#4ba1de',
      padding: 10,
      borderRadius: 5,
      width: '45%',
      alignItems: 'center',
    },
    nextButtonText: {
      color: '#fff',
      fontSize: 16,
    },
    skipButtonText: {
      color: 'black',
      fontWeight:'bold',
      fontSize: 16,
    },
    summaryTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#fff',
      marginBottom: 20,
      textAlign: 'center',
    },
    summaryItem: {
      flexDirection: 'column',
      justifyContent: 'space-between',
      marginVertical: 5,
      width: 300,
    },
    summaryLabel: {
      fontSize: 20,
      color: '#aaa',
      fontWeight: '600',
    },
    summaryValue: {
      fontSize: 18,
      color: '#fff',
    },
    finishButton: {
      backgroundColor: '#007BFF',
      padding: 10,
      borderRadius: 5,
      width: '45%',
      alignItems: 'center',
    },
    finishButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: 'bold',
    },  
    billListContainer: {
      maxHeight: 240,
      width: '100%',
      marginVertical: 10,
      overflow: 'hidden',
    },
    incomeRow: {
      width: '100%',
      flexDirection: 'column',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    removeButton: {
      backgroundColor: '#ff4d4d',
      padding: 8,
      borderRadius: 5,
      alignItems: 'center',
    },
    removeButtonText: {
      color: '#fff',
      fontSize: 14,
    },
    billsHolder:{
      flexDirection: 'row',
      justifyContent:'space-between',
      alignContent: 'center',
    },
    billsContainer:{
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-around',
    },
    billsInput:{
      height: 50,
      width: 100,
      borderRadius: 5,
      paddingHorizontal: 10,
      backgroundColor: '#2a2a3d',
      color: '#fff',
      marginVertical: 10,
      fontSize: 18
    },
    removeBill:{
      color: 'red',
      fontSize: 16,
      marginVertical: 5,
    },
    summaryContainer:{
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 30,
    },
    dDownContainer: {
      marginBottom: 20,
    },
    dDownItem: {
      backgroundColor: '#1E1E1E',
      width: 300,
      padding: 20,
      borderWidth: 1,
      borderRadius: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    dDownText: {
      color: '#FFFFFF',
      fontSize: 18,
      fontWeight: '600',
    },
    expandedContainer: {
      marginTop: 10,
      padding: 15,
      borderWidth: 1,
      borderRadius: 10,
      borderRadius: 10,
      backgroundColor: '#2A2A2A',
      width: 300,
    },
    savedItemContainer: {
      backgroundColor: '#333',
      padding: 15,
      marginBottom: 10,
      borderRadius: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    savedItemText: {
      color: '#FFFFFF',
      fontSize: 16,
    },
    removeText: {
      color: '#FF6347',
      fontSize: 14,
      fontWeight: 'bold',
    },
  });